### ISSUE TITLE
Virgo主题配置记录

### ISSUE THREAD

**Issue by cyolc932** [loveminimal/hugo-theme-virgo#1]
> 2023.2.6

## `config.toml`配置

```toml
baseURL = "https://域名" # 站点URL
languageCode = "zh-cn" # 语言
title = "ABC" # 站名
theme = "virgo" # 主题
googleAnalytics = "G-xxxxxx" 
# 谷歌分析| https://analytics.google.com/analytics/web
# 谷歌SEO| https://search.google.com/search-console

#------------------------------------------#
# 以下为virgo的主题配置
# https://github.com/loveminimal/hugo-theme-virgo
#------------------------------------------#
hasCJKLanguage = true # 有cjk语言
summaryLength = 80    # 摘要长度 默认 70
paginate = 24         # 分页 更好 4 *3 *次
enableGitInfo = true # 启用 git 信息

[params]
    author = '作者'

    #加载页面时激活淡入动画
    hasActiveAnimate = true      

    # 主动炫酷风格，很酷但占用资源多，而且
    # 如果你想替换默认的背景图片，只需
    # 将其重命名为 `default.jpg` 并将其放入 `/static/imgs/bg` 目录，
    # 如 `/static/imgs/bg/default.jpg`。
    hasActiveCool = true  

    # 为了更好的体验，我们使用本地存储来保持主题的黑暗状态，所以
    # 如果你将 dark 设置为 `true` 但没有效果，你
    # 应该清除当前站点的本地存储。和
    # 一般情况下，初次使用是没有任何问题的。
    dark = true

    # 折叠/展开代码块，默认`false`，和
    # 如果 `true` ，所有代码块将在页面加载时折叠。
    # 无论您的设置如何，它在移动视图中始终为true。
    hasFoldAllCodeBlocks = false

    # 激活英文视图，默认中文
    en = true

    slogan = '网站标语'        # 您的网站标语位于标题下方

    # 像下面的项目你需要创建一个相对的 markdown 文件
    # ----------------------------------
    # 搜索-search.md
    # 导航 -nav.md
    # 归档 -archive.md
    # 关于 -about.md 或 about/index.md
    # 想法帖子/idea.md
    # 维基 -posts/wiki.md
    # ----------------------------------
    # 现在，您可以根据需要自定义菜单，并且
    # 更新订单索引号，如 00,01,23...您可以对项目进行排序。
    # ⚓🐶🎉👀💡👓🐌
    [params.menu]
        [params.menu.00]
            active = true
            path = '/nav'
            en = 'Nav'
            zh = '导航'
            icon = '🎯'
        [params.menu.11]
            active = true
            path = '/search'
            en = 'Search'
            zh = '搜索'
            icon = '🔎'
        [params.menu.22]
            active = true
            path = '/posts'
            en = 'Posts'
            zh = '文章'
            icon = '📜'
        [params.menu.33]
            active = true
            path = '/archive'
            en = 'Archive'
            zh = '归档'
            icon = '🎉'
        [params.menu.44]
            active = true
            path = '/wiki'
            en = 'Wiki'
            zh = '百科'
            icon = '🚀'
        [params.menu.55]
            active = true
            path = '/about'
            en = 'About'
            zh = '关于'
            icon = '🐌'

    [params.svg]
        color = '#6c757d'          # icon 颜色 of breadcrumb '#666'  # '#5a29e4' # '#6c757d' 
    
    [params.img]
        # 主页的img -如果不是jpg，重命名，然后
        # 将它放在 inio `static/imgs/` 目录中
        # 内置：lightcolor、girl、wukong 和 tux
        # src = '悟空'
        width = 999
        # 如果不想显示 img 而是显示一些文字，就
        # 评论 `src = 'xxx'`，然后输入你的话：
        # words = "Stay hungry, Stay foolish. Your time is limited, so don't waste it living someone else's life. Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary. -- Steve Jobs."
        # words = "多少事，从来急；天地转，光阴迫。一万年太久，只争朝夕。 -- 教员"
        # words = "你当然会幸福，毕竟我双手合十的愿望都是你。"
        # words = "一个人能控制的，掌握最多主动权的，只是自己。 是的，‘控制’和‘影响’，这就是‘对已’和‘对人’的最大区别！"
        words = "💭您的自定义语句"
        

    [params.contact] # 页面右下角 联系方式 小图标
        icp = ' '                               # 备案号
        icplink = '//beian.miit.gov.cn'
        weibo = 'id'                          # 例如. https://weibo.com/u/id
        wechat = 'imgs/bg/wechat.jpg'         # Wechat QR, choose your path
        email = 'id@outlook.com'
        github = 'id'                         # 例如. https://github.com/id
        bilibili = 'id'                       # 例如. https://space.bilibili.com/id
        twitter = 'id'                        # 例如. https://twitter.com/id
        facebook = 'id'                       # 例如. https://facebook.com/id
        youtube = 'id'                        # 例如. https://youtube.com/user/id
        telegram = 'https://t.me/id' 		# 例如. telegram-=·httos，/web. telegram.org/z
        isShowSlogan = true                 # 例如. show. Contact me.Vla· 展示联系我 
        color = '#696969'                   # 联系人的图标颜色 #5d2f86

[markup]
    [markup.asciidocExt] # Asciidoc扩展
        preserveTOC = true # 保留目录
    [markup.highlight] # 高亮
        style = "github" # 风格
        lineNos = true # 行号
    [markup.tableOfContents] # 目录
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

```

## `posts`文件结构布局

```
content
├─ archive.md # 新增文件：归档页面
├─ nav.md	  # 新增文件：导航页面
├─ posts
│    ├─ Hugo的Virgo主题配置
│    │    └─ index.md
│    ├─ 博文的文章名
│    │    ├─ img
│    │    │    ├─ 1.jpg
│    │    │    ├─ 2.jpg
│    │    │    ├─ 3.jpg
│    │    └─ index.md
└─ search.md   # 新增文件：搜索页面

```

## 图片的引用

- 可参考此`posts`结构

  ```
  content
  ├─ posts
  │    ├─ Hugo 毫秒级 静态框架
  │    │    └─ index.md
  │    ├─ 定期检查名下账号
  │    │    ├─ img
  │    │    │    ├─ 1.jpg
  │    │    │    ├─ 2.jpg
  │    │    │    ├─ 3.jpg
  │    │    └─ index.md
  └─ search.md
  ```

  | 图片路径             | `Markdown`写法                  |
  | -------------------- | ------------------------------- |
  | `static/example.png` | `![example](./img/example.png)` |

- 或者直接放在`static`文件夹内

  | 图片路径             | `Markdown`写法             |
  | -------------------- | -------------------------- |
  | `static/example.png` | `![example](/example.png)` |

##
